[project]
name = "vaccine-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.59.3",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "streamlit>=1.41.1",
]
